# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1178, 712)
        Form.setMinimumSize(QtCore.QSize(1178, 712))
        Form.setWindowIcon(QIcon(':/pic/coloricon.ico'))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeW = QtWidgets.QTreeWidget(Form)
        self.treeW.setHeaderLabels(['数据库'])
        self.treeW.setObjectName("treeW")
        self.horizontalLayout_4.addWidget(self.treeW)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.query_tab = QtWidgets.QWidget()
        self.query_tab.setObjectName("query_tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.query_tab)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.query_tab)
        self.font = QtGui.QFont()
        self.font.setFamily("微软雅黑")
        self.font.setPointSize(12)
        self.textEdit.setFont(self.font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.tabWidget.addTab(self.query_tab, "")
        self.property_tab = QtWidgets.QWidget()
        self.property_tab.setObjectName("property_tab")
        # self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.property_tab)
        # self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        # self.scrollArea_2 = QtWidgets.QScrollArea(self.property_tab)
        # self.scrollArea_2.setWidgetResizable(True)
        # self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 886, 284))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        # self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.userlabel = QtWidgets.QLabel('')
        self.userlabel.setFont(self.font)
        self.font = QtGui.QFont('微软雅黑',10)
        self.switch_btn = QtWidgets.QPushButton("切换用户")
        self.switch_btn.setMinimumSize(121,40)
        self.switch_btn.setFont(self.font)
        self.check_btn = QtWidgets.QPushButton("查看权限")
        self.check_btn.setMinimumSize(121,40)
        self.check_btn.setFont(self.font)
        self.grant_btn = QtWidgets.QPushButton("更改权限")
        self.grant_btn.setMinimumSize(121,40)
        self.grant_btn.setFont(self.font)
        self.revoke_btn = QtWidgets.QPushButton("撤销权限")
        self.revoke_btn.setMinimumSize(121,40)
        self.revoke_btn.setFont(self.font)
        self.horizontalLayout_label = QtWidgets.QHBoxLayout()
        self.horizontalLayout_label.addWidget(self.userlabel, 0 ,QtCore.Qt.AlignCenter)
        self.horizontalLayout_competence = QtWidgets.QHBoxLayout()
        self.horizontalLayout_competence.addStretch(1)
        self.horizontalLayout_competence.addWidget(self.switch_btn)
        self.horizontalLayout_competence.addStretch(1)
        self.horizontalLayout_competence.addWidget(self.check_btn)
        self.horizontalLayout_competence.addStretch(1)
        self.horizontalLayout_competence.addWidget(self.grant_btn)
        self.horizontalLayout_competence.addStretch(1)
        self.horizontalLayout_competence.addWidget(self.revoke_btn)
        self.horizontalLayout_competence.addStretch(1)
        self.verticalLayout_competence = QtWidgets.QVBoxLayout(self.property_tab)
        self.verticalLayout_competence.addLayout(self.horizontalLayout_label)
        self.verticalLayout_competence.addLayout(self.horizontalLayout_competence)

        # self.horizontalLayout_7.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.property_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 1, 15, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.query_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.query_btn.sizePolicy().hasHeightForWidth())
        self.query_btn.setSizePolicy(sizePolicy)
        self.query_btn.setToolTip("执行(F9)")
        self.query_btn.setStyleSheet("QPushButton{border-image:url(:/pic/run.png);}"
                                     "QPushButton:hover{border-image: url(:/pic/run_hover.png);}"
                                     "QPushButton:pressed{border-image: url(:/pic/run_pressed.png);}")
        self.query_btn.setObjectName("query_btn")
        self.query_btn.setShortcut(QtCore.Qt.Key_F9)
        self.horizontalLayout.addWidget(self.query_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.reset_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setToolTip("重置(F10)")
        self.reset_btn.setStyleSheet("QPushButton{border-image:url(:/pic/reset.png);}"
                                     "QPushButton:hover{border-image: url(:/pic/reset_hover.png);}"
                                     "QPushButton:pressed{border-image: url(:/pic/reset_pressed.png);}")
        self.reset_btn.setObjectName("reset_btn")
        self.reset_btn.setShortcut(QtCore.Qt.Key_F10)
        self.reset_btn.clicked.connect(self.textEdit.clear)
        self.horizontalLayout.addWidget(self.reset_btn)
        self.horizontalLayout.setStretch(0, 15)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 890, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        # self.tableView.setObjectName("tableView")
        # self.horizontalLayout_2.addWidget(self.tableView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.query_tab), _translate("Form", "Query"))
        self.tabWidget.setFont(QtGui.QFont('微软雅黑',10))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.property_tab), _translate("Form", "权限"))
        self.groupBox.setTitle(_translate("Form", "结果"))

import apprcc_rc
